cabal-version: 2.4
name: pm-wspr
version: 0.1.0.0
synopsis: WSPR 162-symbol 4-FSK sequencer - blockRam symbol table, NCO phase-inc out, TX interlock
build-type: Simple

common shared
  default-language: Haskell2010
  ghc-options: -Wall -fplugin GHC.TypeLits.Extra.Solver -fplugin GHC.TypeLits.Normalise -fplugin GHC.TypeLits.KnownNat.Solver
  build-depends: base, Cabal, clash-prelude >= 1.8, ghc-typelits-natnormalise, ghc-typelits-extra, ghc-typelits-knownnat
  default-extensions:
    BangPatterns BinaryLiterals ConstraintKinds DataKinds DefaultSignatures
    DeriveAnyClass DeriveGeneric DerivingStrategies FlexibleContexts
    KindSignatures MagicHash NoStarIsType NumericUnderscores
    ScopedTypeVariables TemplateHaskell TypeApplications TypeFamilies
    TypeOperators NoImplicitPrelude

library
  import: shared
  hs-source-dirs: src
  exposed-modules: PM.Wspr

test-suite wspr-test
  import: shared
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Spec.hs
  build-depends: pm-wspr
  ghc-options: -threaded

executable clash
  import: shared
  main-is: bin/Clash.hs
  build-depends: clash-ghc

test-suite wspr-fsk-test
  import: shared
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: FskSpec.hs
  build-depends: pm-wspr
  ghc-options: -threaded
