-- cic_dec_tb: golden-model comparison for the CIC decimator (maiden34).
--
-- Reads build/vectors/cic_stim.txt (one "i q" pair per line) generated by
-- golden/model.py (fixed seed), drives the DUT at one sample per 4 clocks,
-- and compares every decimated output against build/vectors/cic_exp.txt.
-- The golden model is bit-true, so the pass tolerance of +/-2 LSB is
-- expected to close at exactly 0 LSB; any nonzero delta is reported.
--
-- Asserts are requirement-tagged: GS-002.

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use std.textio.all;

entity cic_dec_tb is
end entity;

architecture sim of cic_dec_tb is
  constant CLK_PERIOD : time := 83.333 ns;  -- 12 MHz
  constant TOL        : integer := 2;       -- LSB

  signal clk     : std_logic := '0';
  signal rst     : std_logic := '1';
  signal in_i    : signed(15 downto 0) := (others => '0');
  signal in_q    : signed(15 downto 0) := (others => '0');
  signal in_stb  : std_logic := '0';
  signal out_i   : signed(15 downto 0);
  signal out_q   : signed(15 downto 0);
  signal out_stb : std_logic;
  signal done    : boolean := false;
begin

  dut : entity work.cic_dec
    generic map (N => 3, R => 4, W_IN => 16)
    port map (clk => clk, rst => rst,
              in_i => in_i, in_q => in_q, in_stb => in_stb,
              out_i => out_i, out_q => out_q, out_stb => out_stb);

  clk <= not clk after CLK_PERIOD / 2 when not done else '0';

  stimulus : process
    file f     : text open read_mode is "build/vectors/cic_stim.txt";
    variable l : line;
    variable vi, vq : integer;
  begin
    wait for 5 * CLK_PERIOD;
    wait until rising_edge(clk);
    rst <= '0';
    while not endfile(f) loop
      readline(f, l);
      read(l, vi);
      read(l, vq);
      in_i   <= to_signed(vi, 16);
      in_q   <= to_signed(vq, 16);
      in_stb <= '1';
      wait until rising_edge(clk);
      in_stb <= '0';
      wait until rising_edge(clk);
      wait until rising_edge(clk);
      wait until rising_edge(clk);
    end loop;
    wait for 10 * CLK_PERIOD;
    done <= true;
    wait;
  end process;

  checker : process
    file f     : text open read_mode is "build/vectors/cic_exp.txt";
    variable l : line;
    variable ei, eq : integer;
    variable n_out  : integer := 0;
    variable worst  : integer := 0;
    variable d      : integer;
  begin
    while not endfile(f) loop
      readline(f, l);
      read(l, ei);
      read(l, eq);
      loop
        wait until rising_edge(clk);
        exit when out_stb = '1';
      end loop;
      d := abs(to_integer(out_i) - ei);
      if abs(to_integer(out_q) - eq) > d then
        d := abs(to_integer(out_q) - eq);
      end if;
      if d > worst then
        worst := d;
      end if;
      assert d <= TOL
        report "GS-002 FAIL: sample " & integer'image(n_out) &
               " delta " & integer'image(d) & " LSB (got " &
               integer'image(to_integer(out_i)) & "," &
               integer'image(to_integer(out_q)) & " want " &
               integer'image(ei) & "," & integer'image(eq) & ")"
        severity failure;
      n_out := n_out + 1;
    end loop;
    report "GS-002 pass: cic_dec matches golden model, " &
           integer'image(n_out) & " outputs, worst delta " &
           integer'image(worst) & " LSB (tol " & integer'image(TOL) & ")";
    wait;
  end process;

end architecture;
