/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.5. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module pm_zones
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire [11:0] s2_adc
    , input wire [11:0] s3_adc
    , input wire [11:0] s4_adc

      // Outputs
    , output wire [15:0] ipanel
    , output wire [2:0] mode
    , output wire  mode_change
    );
  reg [2:0] s1 = 3'd0;
  wire [15:0] y;
  wire signed [63:0] result_0;
  wire signed [63:0] c$case_alt;
  wire [2:0] result_1;
  wire [2:0] result_2;
  wire [2:0] c$s1_case_alt;
  wire [2:0] c$s1_case_alt_0;
  wire [15:0] y_0;
  wire signed [63:0] result_3;
  wire signed [63:0] c$case_alt_0;
  wire [12:0] r;
  wire [11:0] result_4;
  wire [15:0] y_1;
  wire signed [63:0] result_5;
  wire signed [63:0] c$case_alt_1;
  wire [12:0] r_0;
  wire [11:0] result_6;
  reg [1:0] s1_0 = 2'd0;
  wire [15:0] y_2;
  wire signed [63:0] result_7;
  wire signed [63:0] c$case_alt_2;
  wire [1:0] result_8;
  wire [1:0] result_9;
  wire [1:0] c$s1_case_alt_1;
  wire [1:0] c$s1_case_alt_2;
  wire [15:0] y_3;
  wire signed [63:0] result_10;
  wire signed [63:0] c$case_alt_3;
  wire [12:0] r_1;
  wire [11:0] result_11;
  wire [15:0] y_4;
  wire signed [63:0] result_12;
  wire signed [63:0] c$case_alt_4;
  wire [12:0] r_2;
  wire [11:0] result_13;
  reg [1:0] s1_1 = 2'd0;
  wire [15:0] y_5;
  wire signed [63:0] result_14;
  wire signed [63:0] c$case_alt_5;
  wire [1:0] result_15;
  wire [1:0] result_16;
  wire [1:0] c$s1_case_alt_3;
  wire [1:0] c$s1_case_alt_4;
  wire [15:0] y_6;
  wire signed [63:0] result_17;
  wire signed [63:0] c$case_alt_6;
  wire [12:0] r_3;
  wire [11:0] result_18;
  wire [15:0] y_7;
  wire signed [63:0] result_19;
  wire signed [63:0] c$case_alt_7;
  wire [12:0] r_4;
  wire [11:0] result_20;
  wire [38:0] result_21;
  wire [38:0] c$case_alt_8;
  wire [32:0] r_5;
  wire [31:0] result_22;
  wire [0:0] c$app_arg;
  wire  stable;
  reg [38:0] s1_2 = {3'd0,   3'd0,   32'd0,   1'b0};
  wire [0:0] c$case_alt_9;
  wire [11:0] c$bv;
  wire [12:0] c$bv_0;
  wire [12:0] c$bv_1;
  wire [11:0] c$bv_2;
  wire [12:0] c$bv_3;
  wire [12:0] c$bv_4;
  wire [11:0] c$bv_5;
  wire [12:0] c$bv_6;
  wire [12:0] c$bv_7;
  wire [32:0] c$bv_8;
  wire [27:0] c$case_alt_selection_3;
  wire [27:0] result_dc_arg_0;
  wire [27:0] result_dc_arg_4;
  wire [19:0] result;

  // register begin
  always @(posedge clk or  posedge  rst) begin : s1_register
    if ( rst) begin
      s1 <= 3'd0;
    end else if (en) begin
      s1 <= result_2;
    end
  end
  // register end

  assign c$bv = (s3_adc);

  assign y = (({{(16-12) {1'b0}},(s3_adc)}) * 16'd6) >> (64'sd12);

  assign result_0 = (16'd5 <= y) ? 64'sd5 : c$case_alt;

  assign c$case_alt = $unsigned({{(64-16) {1'b0}},y});

  assign result_1 = $unsigned(result_0[0+:3]);

  assign result_2 = (result_1 == s1) ? s1 : c$s1_case_alt;

  assign c$s1_case_alt = ((result_1 > s1) & (($unsigned(result_5[0+:3])) > s1)) ? result_1 : c$s1_case_alt_0;

  assign c$s1_case_alt_0 = ((result_1 < s1) & (($unsigned(result_3[0+:3])) < s1)) ? result_1 : s1;

  assign y_0 = (({{(16-12) {1'b0}},result_4}) * 16'd6) >> (64'sd12);

  assign result_3 = (16'd5 <= y_0) ? 64'sd5 : c$case_alt_0;

  assign c$case_alt_0 = $unsigned({{(64-16) {1'b0}},y_0});

  assign r = (s3_adc) + 12'd128;

  assign c$bv_0 = ((r));

  assign result_4 = (( c$bv_0[13-1] ) == 1'b0) ? (r[0+:12]) : 12'd4095;

  assign y_1 = (({{(16-12) {1'b0}},result_6}) * 16'd6) >> (64'sd12);

  assign result_5 = (16'd5 <= y_1) ? 64'sd5 : c$case_alt_1;

  assign c$case_alt_1 = $unsigned({{(64-16) {1'b0}},y_1});

  assign r_0 =  (s3_adc) - 12'd128;

  assign c$bv_1 = ((r_0));

  assign result_6 = (( c$bv_1[13-1] ) == 1'b0) ? (r_0[0+:12]) : (12'd0);

  // register begin
  always @(posedge clk or  posedge  rst) begin : s1_0_register
    if ( rst) begin
      s1_0 <= 2'd0;
    end else if (en) begin
      s1_0 <= result_9;
    end
  end
  // register end

  assign c$bv_2 = (s2_adc);

  assign y_2 = (({{(16-12) {1'b0}},(s2_adc)}) * 16'd3) >> (64'sd12);

  assign result_7 = (16'd2 <= y_2) ? 64'sd2 : c$case_alt_2;

  assign c$case_alt_2 = $unsigned({{(64-16) {1'b0}},y_2});

  assign result_8 = $unsigned(result_7[0+:2]);

  assign result_9 = (result_8 == s1_0) ? s1_0 : c$s1_case_alt_1;

  assign c$s1_case_alt_1 = ((result_8 > s1_0) & (($unsigned(result_12[0+:2])) > s1_0)) ? result_8 : c$s1_case_alt_2;

  assign c$s1_case_alt_2 = ((result_8 < s1_0) & (($unsigned(result_10[0+:2])) < s1_0)) ? result_8 : s1_0;

  assign y_3 = (({{(16-12) {1'b0}},result_11}) * 16'd3) >> (64'sd12);

  assign result_10 = (16'd2 <= y_3) ? 64'sd2 : c$case_alt_3;

  assign c$case_alt_3 = $unsigned({{(64-16) {1'b0}},y_3});

  assign r_1 = (s2_adc) + 12'd128;

  assign c$bv_3 = ((r_1));

  assign result_11 = (( c$bv_3[13-1] ) == 1'b0) ? (r_1[0+:12]) : 12'd4095;

  assign y_4 = (({{(16-12) {1'b0}},result_13}) * 16'd3) >> (64'sd12);

  assign result_12 = (16'd2 <= y_4) ? 64'sd2 : c$case_alt_4;

  assign c$case_alt_4 = $unsigned({{(64-16) {1'b0}},y_4});

  assign r_2 =  (s2_adc) - 12'd128;

  assign c$bv_4 = ((r_2));

  assign result_13 = (( c$bv_4[13-1] ) == 1'b0) ? (r_2[0+:12]) : (12'd0);

  // register begin
  always @(posedge clk or  posedge  rst) begin : s1_1_register
    if ( rst) begin
      s1_1 <= 2'd0;
    end else if (en) begin
      s1_1 <= result_16;
    end
  end
  // register end

  assign c$bv_5 = (s4_adc);

  assign y_5 = (({{(16-12) {1'b0}},(s4_adc)}) * 16'd4) >> (64'sd12);

  assign result_14 = (16'd3 <= y_5) ? 64'sd3 : c$case_alt_5;

  assign c$case_alt_5 = $unsigned({{(64-16) {1'b0}},y_5});

  assign result_15 = $unsigned(result_14[0+:2]);

  assign result_16 = (result_15 == s1_1) ? s1_1 : c$s1_case_alt_3;

  assign c$s1_case_alt_3 = ((result_15 > s1_1) & (($unsigned(result_19[0+:2])) > s1_1)) ? result_15 : c$s1_case_alt_4;

  assign c$s1_case_alt_4 = ((result_15 < s1_1) & (($unsigned(result_17[0+:2])) < s1_1)) ? result_15 : s1_1;

  assign y_6 = (({{(16-12) {1'b0}},result_18}) * 16'd4) >> (64'sd12);

  assign result_17 = (16'd3 <= y_6) ? 64'sd3 : c$case_alt_6;

  assign c$case_alt_6 = $unsigned({{(64-16) {1'b0}},y_6});

  assign r_3 = (s4_adc) + 12'd128;

  assign c$bv_6 = ((r_3));

  assign result_18 = (( c$bv_6[13-1] ) == 1'b0) ? (r_3[0+:12]) : 12'd4095;

  assign y_7 = (({{(16-12) {1'b0}},result_20}) * 16'd4) >> (64'sd12);

  assign result_19 = (16'd3 <= y_7) ? 64'sd3 : c$case_alt_7;

  assign c$case_alt_7 = $unsigned({{(64-16) {1'b0}},y_7});

  assign r_4 =  (s4_adc) - 12'd128;

  assign c$bv_7 = ((r_4));

  assign result_20 = (( c$bv_7[13-1] ) == 1'b0) ? (r_4[0+:12]) : (12'd0);

  assign result_21 = ((result_22 >= 32'd25000000) & (s1_2[38:36] != s1)) ? {s1,
                                                                            s1,   result_22,   1'b1} : {s1_2[38:36],
                                                                                                        s1,
                                                                                                        result_22,
                                                                                                        1'b0};

  assign c$case_alt_8 = (s1 != s1_2[35:33]) ? {s1_2[38:36],
                                               s1,   32'd0,   1'b0} : result_21;

  assign r_5 = s1_2[32:1] + 32'd1;

  assign c$bv_8 = ((r_5));

  assign result_22 = (( c$bv_8[33-1] ) == 1'b0) ? (r_5[0+:32]) : 32'd4294967295;

  assign c$app_arg = stable ? 1'b1 : 1'b0;

  assign stable = s1_2[32:1] >= 32'd25000000;

  // register begin
  always @(posedge clk or  posedge  rst) begin : s1_2_register
    if ( rst) begin
      s1_2 <= {3'd0,   3'd0,   32'd0,   1'b0};
    end else if (en) begin
      s1_2 <= c$case_alt_8;
    end
  end
  // register end

  assign c$case_alt_selection_3 = {s1_0,   s1,
                                   s1_1,   stable,   s1_2[38:36],   s1_2[0:0],
                                   {({({({({(c$app_arg),7'b0000000}),((s1_0))}),((s1_1))}),1'b0}),((s1))}};

  assign c$case_alt_9 = c$case_alt_selection_3[16:16] ? 1'b1 : 1'b0;

  assign result_dc_arg_0 = {s1_0,   s1,   s1_1,
                            stable,   s1_2[38:36],   s1_2[0:0],
                            {({({({({(c$app_arg),7'b0000000}),((s1_0))}),((s1_1))}),1'b0}),((s1))}};

  assign result_dc_arg_4 = {s1_0,   s1,   s1_1,
                            stable,   s1_2[38:36],   s1_2[0:0],
                            {({({({({(c$app_arg),7'b0000000}),((s1_0))}),((s1_1))}),1'b0}),((s1))}};

  assign result = {result_dc_arg_0[15:0],
                   (result_dc_arg_4[19:17]),   (c$case_alt_9)};

  assign ipanel = result[19:4];

  assign mode = result[3:1];

  assign mode_change = result[0:0];


endmodule

