/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.5. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module pm_harplink
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire [7:0] divisor
    , input wire [48:0] tx_frame
    , input wire  rx_line

      // Outputs
    , output wire [50:0] out
    );
  reg [67:0] c$ds_app_arg = {{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
  8'b00000000,   8'b00000000,   8'b00000000},   4'd0};
  reg [21:0] c$ds_app_arg_0 = {1'b0,   1'b0,   8'b00000000,   4'd0,   8'd0};
  wire [30:0] c$case_alt;
  wire [30:0] c$case_alt_0;
  wire [30:0] c$case_alt_1;
  wire [30:0] c$case_alt_2;
  wire [30:0] c$case_alt_3;
  wire [8:0] c$app_arg;
  wire  c$case_scrut;
  wire [116:0] result;
  wire [116:0] result_0;
  wire [116:0] c$case_alt_4;
  wire [116:0] result_1;
  wire [55:0] ds;
  wire [48:0] result_2;
  wire [7:0] c$app_arg_0;
  wire [7:0] c$app_arg_1;
  wire [7:0] c$app_arg_2;
  wire [7:0] c$app_arg_3;
  wire [7:0] c$app_arg_4;
  wire [7:0] c$app_arg_5;
  wire [63:0] ws1;
  wire [55:0] ws2;
  wire [3:0] \got' ;
  wire [7:0] ipv;
  reg [8:0] c$ds_app_arg_1 = {1'b0,8'bxxxxxxxx};
  reg [22:0] c$ds_app_arg_2 = {1'b0,   10'b1111111111,   4'd0,   8'd0};
  wire [24:0] c$case_alt_5;
  wire [24:0] c$case_alt_6;
  wire [24:0] c$case_alt_7;
  wire [7:0] b;
  wire [24:0] c$case_alt_8;
  wire [7:0] c$app_arg_6;
  reg [79:0] c$ds2_app_arg = {{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
  8'b00000000,   8'b00000000,   8'b00000000},   4'd0,   12'd0};
  wire [89:0] c$case_alt_9;
  wire [89:0] c$case_alt_10;
  wire [47:0] f;
  wire [7:0] bs;
  wire [15:0] bs1;
  wire [23:0] bs2;
  wire [31:0] bs3;
  wire [39:0] bs4;
  wire [47:0] bs5;
  wire [55:0] bs7;
  wire [63:0] ws1_0;
  wire [55:0] ws2_0;
  wire [89:0] result_3;
  wire [11:0] c$app_arg_7;
  wire [89:0] c$case_alt_11;
  wire [89:0] result_4;
  wire  txReady;
  wire [7:0] c$bv;
  wire [8:0] result_selection_1;
  wire [71:0] result_sel_alt_f_2;
  wire [71:0] ds_1;
  wire [63:0] c$vec;
  wire [71:0] result_selection_4_3;
  wire [63:0] c$vec_0;
  wire [55:0] c$vec2;
  wire [9:0] c$bv_0;
  wire [9:0] c$bv_1;
  wire [9:0] c$bv_2;
  wire [55:0] c$vec2_0;
  wire [71:0] c$case_alt_sel_alt_t_30;
  wire [63:0] c$vec_1;

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds_app_arg_register
    if ( rst) begin
      c$ds_app_arg <= {{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
    8'b00000000,   8'b00000000,   8'b00000000},   4'd0};
    end else if (en) begin
      c$ds_app_arg <= result[116:49];
    end
  end
  // register end

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds_app_arg_0_register
    if ( rst) begin
      c$ds_app_arg_0 <= {1'b0,   1'b0,   8'b00000000,   4'd0,   8'd0};
    end else if (en) begin
      c$ds_app_arg_0 <= c$case_alt[30:9];
    end
  end
  // register end

  assign c$case_alt = (~ c$ds_app_arg_0[21:21]) ? c$case_alt_0 : c$case_alt_1;

  assign c$case_alt_0 = c$case_scrut ? {{c$ds_app_arg_0[21:21],
                                         1'b1,   c$ds_app_arg_0[19:12],
                                         c$ds_app_arg_0[11:8],   c$ds_app_arg_0[7:0]},
                                        {1'b0,8'bxxxxxxxx}} : c$case_alt_2;

  assign c$case_alt_1 = (c$ds_app_arg_0[7:0] != 8'd0) ? {{c$ds_app_arg_0[21:21],
                                                          c$ds_app_arg_0[20:20],
                                                          c$ds_app_arg_0[19:12],   c$ds_app_arg_0[11:8],
                                                          c$ds_app_arg_0[7:0] - 8'd1},
                                                         {1'b0,8'bxxxxxxxx}} : c$case_alt_3;

  assign c$case_alt_2 = c$ds_app_arg_0[20:20] ? {{1'b1,
                                                  1'b0,   8'b00000000,   4'd8,
                                                  (divisor + (divisor >> (64'sd1))) - 8'd1},
                                                 {1'b0,8'bxxxxxxxx}} : {c$ds_app_arg_0,
                                                                        {1'b0,8'bxxxxxxxx}};

  assign c$bv = (c$ds_app_arg_0[19:12]);

  assign c$case_alt_3 = (c$ds_app_arg_0[11:8] != 4'd0) ? {{c$ds_app_arg_0[21:21],
                                                           c$ds_app_arg_0[20:20],
                                                           {((rx_line)),(c$bv[7 : 1])},
                                                           c$ds_app_arg_0[11:8] - 4'd1,
                                                           divisor - 8'd1},
                                                          {1'b0,8'bxxxxxxxx}} : {{1'b0,
                                                                                  c$ds_app_arg_0[20:20],
                                                                                  c$ds_app_arg_0[19:12],
                                                                                  c$ds_app_arg_0[11:8],
                                                                                  c$ds_app_arg_0[7:0]},   c$app_arg};

  assign c$app_arg = c$case_scrut ? {1'b1,c$ds_app_arg_0[19:12]} : {1'b0,8'bxxxxxxxx};

  assign c$case_scrut = rx_line == 1'b1;

  assign result_selection_1 = c$case_alt[8:0];

  assign result = result_selection_1[8:8] ? result_0 : {c$ds_app_arg,
                                                        {1'b0,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  assign result_0 = (c$ds_app_arg[3:0] == 4'd0) ? c$case_alt_4 : result_1;

  assign c$case_alt_4 = (ipv != 8'b10100101) ? {c$ds_app_arg,
                                                {1'b0,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}} : result_1;

  assign result_sel_alt_f_2 = ({c$ds_app_arg[67:4],ipv});

  assign result_1 = (\got'  == 4'd8) ? {{{8 {8'b00000000}},
                                         4'd0},
                                        result_2} : {{result_sel_alt_f_2[63:0],
                                                      \got' },
                                                     {1'b0,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};

  assign ds_1 = ({c$ds_app_arg[67:4],ipv});

  assign c$vec = ds_1[63:0];

  assign ds = c$vec[64-1 : 8];

  assign result_selection_4_3 = ({c$ds_app_arg[67:4],ipv});

  assign c$vec_0 = result_selection_4_3[63:0];

  assign result_2 = (((ds[56-1 -: 8]) == 8'b10100101) & ((ws1[8-1:0]) == (c$vec_0[8-1:0]))) ? {1'b1,{c$app_arg_5,
                                                                                                     c$app_arg_4,
                                                                                                     c$app_arg_3,
                                                                                                     c$app_arg_2,
                                                                                                     c$app_arg_1,
                                                                                                     c$app_arg_0}} : {1'b0,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$app_arg_0 = ds[7:0];

  assign c$app_arg_1 = ds[15:8];

  assign c$app_arg_2 = ds[23:16];

  assign c$app_arg_3 = ds[31:24];

  assign c$app_arg_4 = ds[39:32];

  assign c$app_arg_5 = ds[47:40];

  assign ws1 = {8'b00000000,   ws2};

  assign c$vec2 = (ws1[64-1 : 8]);

  // zipWith start
  genvar i;
  generate
  for (i = 0; i < 7; i = i + 1) begin : zipWith
    wire [7:0] zipWith_in1;
    assign zipWith_in1 = ds[i*8+:8];
    wire [7:0] zipWith_in2;
    assign zipWith_in2 = c$vec2[i*8+:8];
    wire [7:0] c$n;
    assign c$n = zipWith_in2 + zipWith_in1;


    assign ws2[i*8+:8] = c$n;
  end
  endgenerate
  // zipWith end

  assign \got'  = c$ds_app_arg[3:0] + 4'd1;

  assign ipv = c$case_alt[7:0];

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds_app_arg_1_register
    if ( rst) begin
      c$ds_app_arg_1 <= {1'b0,8'bxxxxxxxx};
    end else if (en) begin
      c$ds_app_arg_1 <= result_4[9:1];
    end
  end
  // register end

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds_app_arg_2_register
    if ( rst) begin
      c$ds_app_arg_2 <= {1'b0,   10'b1111111111,   4'd0,   8'd0};
    end else if (en) begin
      c$ds_app_arg_2 <= c$case_alt_5[24:2];
    end
  end
  // register end

  assign c$case_alt_5 = (~ c$ds_app_arg_2[22:22]) ? c$case_alt_6 : c$case_alt_7;

  assign c$case_alt_6 = c$ds_app_arg_1[8:8] ? {{1'b1,
                                                {({(1'b1),b}),(1'b0)},   4'd10,
                                                c$app_arg_6},   {1'b1,
                                                                 1'b0}} : {c$ds_app_arg_2,   {1'b1,   1'b1}};

  assign c$bv_0 = (c$ds_app_arg_2[21:12]);

  assign c$case_alt_7 = (c$ds_app_arg_2[7:0] != 8'd0) ? {{c$ds_app_arg_2[22:22],
                                                          c$ds_app_arg_2[21:12],   c$ds_app_arg_2[11:8],
                                                          c$ds_app_arg_2[7:0] - 8'd1},   { c$bv_0[0] ,
                                                                                          1'b0}} : c$case_alt_8;

  assign b = c$ds_app_arg_1[7:0];

  assign c$bv_1 = (c$ds_app_arg_2[21:12]);

  assign c$bv_2 = (c$ds_app_arg_2[21:12]);

  assign c$case_alt_8 = (c$ds_app_arg_2[11:8] == 4'd1) ? {{1'b0,
                                                           c$ds_app_arg_2[21:12],   c$ds_app_arg_2[11:8],
                                                           c$ds_app_arg_2[7:0]},   { c$bv_1[0] ,
                                                                                    1'b0}} : {{c$ds_app_arg_2[22:22],
                                                                                               c$ds_app_arg_2[21:12] >> (64'sd1),
                                                                                               c$ds_app_arg_2[11:8] - 4'd1,
                                                                                               c$app_arg_6},
                                                                                              { c$bv_2[0] ,   1'b0}};

  assign c$app_arg_6 = divisor - 8'd1;

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds2_app_arg_register
    if ( rst) begin
      c$ds2_app_arg <= {{8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,   8'b00000000,
    8'b00000000,   8'b00000000,   8'b00000000},   4'd0,   12'd0};
    end else if (en) begin
      c$ds2_app_arg <= result_4[89:10];
    end
  end
  // register end

  assign c$case_alt_9 = (c$ds2_app_arg[11:0] != 12'd0) ? {{c$ds2_app_arg[79:16],
                                                           c$ds2_app_arg[15:12],
                                                           c$ds2_app_arg[11:0] - 12'd1},
                                                          {{1'b0,8'bxxxxxxxx},   1'b0}} : c$case_alt_10;

  assign c$case_alt_10 = tx_frame[48:48] ? {{{bs7,ws1_0[8-1:0]},
                                             4'd8,   12'd0},   {{1'b0,8'bxxxxxxxx},
                                                                1'b0}} : {c$ds2_app_arg,
                                                                          {{1'b0,8'bxxxxxxxx},   1'b1}};

  assign f = tx_frame[47:0];

  assign bs = f[7:0];

  assign bs1 = {f[15:8],   bs};

  assign bs2 = {f[23:16],   bs1};

  assign bs3 = {f[31:24],   bs2};

  assign bs4 = {f[39:32],   bs3};

  assign bs5 = {f[47:40],   bs4};

  assign bs7 = {8'b10100101,   bs5};

  assign ws1_0 = {8'b00000000,   ws2_0};

  assign c$vec2_0 = (ws1_0[64-1 : 8]);

  // zipWith start
  genvar i_0;
  generate
  for (i_0 = 0; i_0 < 7; i_0 = i_0 + 1) begin : zipWith_0
    wire [7:0] zipWith_in1_0;
    assign zipWith_in1_0 = bs7[i_0*8+:8];
    wire [7:0] zipWith_in2_0;
    assign zipWith_in2_0 = c$vec2_0[i_0*8+:8];
    wire [7:0] c$n_0;
    assign c$n_0 = zipWith_in2_0 + zipWith_in1_0;


    assign ws2_0[i_0*8+:8] = c$n_0;
  end
  endgenerate
  // zipWith end

  assign result_3 = (c$ds2_app_arg[15:12] != 4'd0) ? {c$ds2_app_arg,
                                                      {{1'b0,8'bxxxxxxxx},   1'b0}} : c$case_alt_9;

  assign c$app_arg_7 = (c$ds2_app_arg[15:12] == 4'd1) ? (12'd15 * ({{(12-8) {1'b0}},divisor})) : c$ds2_app_arg[11:0];

  assign c$case_alt_sel_alt_t_30 = ({c$ds2_app_arg[79:16],8'b00000000});

  assign c$vec_1 = c$ds2_app_arg[79:16];

  assign c$case_alt_11 = txReady ? {{c$case_alt_sel_alt_t_30[63:0],
                                     c$ds2_app_arg[15:12] - 4'd1,   c$app_arg_7},
                                    {{1'b1,c$vec_1[64-1 -: 8]},
                                     1'b0}} : result_3;

  assign result_4 = (c$ds2_app_arg[15:12] != 4'd0) ? c$case_alt_11 : result_3;

  assign txReady = c$case_alt_5[0:0];

  assign out = {{c$case_alt_5[1:1],
                 result_4[0:0]},   result[48:0]};


endmodule

