"""maiden23 + maiden25: fusion end to end on twin data, with evidence.

Evidence files (results/lesson12/, results/lesson13/) are regenerated by
this suite from real runs — the numbers in them are never typed in.
SYS-002/003/004 numbers here are SIM REHEARSAL results: necessary, not
sufficient. VT-10/11/12 bind only on the field campaign (lesson 99).
"""

from pathlib import Path

import matplotlib
import numpy as np
import pytest

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from maiden.fuse import (
    Ekf,
    EkfConfig,
    fuse,
    fuse_azel_only,
    fuse_session,
    h_azel,
    is_valid,
)
from maiden.geo import Pose
from maiden.state import StateSample
from maiden.twin.model import sportsman
from maiden.twin.sensors import observe
from maiden.twin.writer import default_poses, write_session

RESULTS12 = Path("results/lesson12")
RESULTS13 = Path("results/lesson13")

# SYS-002/003/004 sim-rehearsal thresholds from their single numeric
# home (maiden28); D2 is the authority for the values.
from maiden.validate import (
    CONTINUITY_MIN,
)
from maiden.validate import (
    POS_RMS_MAX_M as POS_RMS_MAX,
)
from maiden.validate import (
    VEL_RMS_MAX_MPS as VEL_RMS_MAX,
)


def _streams_to_samples(streams_by_name):
    out = []
    for name, st in streams_by_name.items():
        for t, az, el, conf in st.tracker:
            out.append(StateSample(t_utc=float(t), source=name,
                                   az_deg=float(az), el_deg=float(el),
                                   conf=float(conf)))
        for t, vr, _snr in st.radar:
            out.append(StateSample(t_utc=float(t), source=name,
                                   v_r=float(vr)))
    out.sort(key=lambda s: s.t_utc)
    return out


def _truth_at(truth, times):
    pos = np.column_stack([np.interp(times, truth.t, truth.pos_enu[:, i])
                           for i in range(3)])
    vel = np.column_stack([np.interp(times, truth.t, truth.vel_enu[:, i])
                           for i in range(3)])
    return pos, vel


def _rms(err):
    return float(np.sqrt(np.mean(np.sum(np.square(err), axis=1))))


@pytest.fixture(scope="module")
def clean_ab():
    """Strict maiden23 case: noise on, dropouts OFF, no outage, A+B."""
    truth = sportsman(seed=202)
    poses, _ = default_poses()
    streams = {n: observe(truth, poses[n],
                          rng=np.random.default_rng(500 + ord(n)),
                          dropout_p=0.0, outage=None)
               for n in ("A", "B")}
    return truth, poses, _streams_to_samples(streams)


@pytest.fixture(scope="module")
def imperfect_session(tmp_path_factory):
    out = tmp_path_factory.mktemp("twin-headline")
    paths = write_session(out, seed=303, imperfect=True)
    return out, paths, np.load(paths["npz"])


def test_azel_only_clean_rms(clean_ab):
    """maiden23: A+B angles only; RMS at the D3-predicted order; evidence."""
    truth, poses, samples = clean_ab
    fused = fuse_azel_only(samples, {"A": poses["A"], "B": poses["B"]})
    t = np.array([s.t_utc for s in fused])
    p = np.array([s.pos_enu for s in fused])
    v = np.array([s.vel_enu for s in fused])
    tp, tv = _truth_at(truth, t)
    pos_rms, vel_rms = _rms(p - tp), _rms(v - tv)

    RESULTS12.mkdir(parents=True, exist_ok=True)
    # sigma_a sweep, A+B clean — the EkfConfig default cites this file
    sweep = {}
    for sig in (5.0, 10.0, 20.0, 40.0):
        cfg_fused = _run_azel_with_sigma(samples, poses, sig)
        st = np.array([s.t_utc for s in cfg_fused])
        sp = np.array([s.pos_enu for s in cfg_fused])
        sweep[sig] = _rms(sp - _truth_at(truth, st)[0])
    with open(RESULTS12 / "rms.txt", "w") as f:
        f.write("maiden23 clean A+B run (twin seed 202, dropouts off)\n")
        f.write(f"pos RMS = {pos_rms:.3f} m   vel RMS = {vel_rms:.3f} m/s "
                "(angles only; mediocre by design — maiden24's motivation)\n")
        f.write("sigma_a sweep (pos RMS, m): "
                + "  ".join(f"{k:g}->{v:.3f}" for k, v in sweep.items())
                + "\n")

    fig, axes = plt.subplots(3, 1, figsize=(10, 7), sharex=True)
    for i, name in enumerate("ENU"):
        axes[i].plot(truth.t, truth.pos_enu[:, i], "k-", lw=0.8,
                     label="truth")
        axes[i].plot(t, p[:, i], "r.", ms=1.5, label="fused")
        axes[i].set_ylabel(name + " (m)")
    axes[0].legend()
    axes[0].set_title(f"A+B az/el only, clean twin: pos RMS {pos_rms:.3f} m")
    axes[2].set_xlabel("t (s)")
    fig.savefig(RESULTS12 / "fused_vs_truth_ab.png", dpi=110)
    plt.close(fig)

    assert pos_rms < 1.0, f"A+B clean pos RMS {pos_rms:.3f} m"
    # no divergence anywhere (max error bounded)
    assert np.abs(p - tp).max() < 10.0
    # sweep sanity: the chosen default (20) is within 20% of the best
    assert sweep[20.0] < 1.2 * min(sweep.values())


def _run_azel_with_sigma(samples, poses, sigma_a):
    from maiden import fuse as fz
    stations = {"A": poses["A"], "B": poses["B"]}
    ekf = Ekf(EkfConfig(sigma_a=sigma_a))
    out = []
    pending = {}
    for m in fz._azel_streams(samples):
        t, src, az, el = m
        if src not in stations:
            continue
        if ekf.x is None:
            fz._try_init(ekf, pending, m, stations)
            continue
        ekf.predict(t)
        if ekf.update_azel((az, el), stations[src]):
            out.append(ekf.fused_sample())
    return out


def test_headline_imperfect_session(imperfect_session):
    """maiden25 headline: 3 stations, imperfect twin, from .ch10 files."""
    out_dir, _paths, npz = imperfect_session
    (fused, stats), _stations = fuse_session(out_dir)
    assert stats.n_epochs > 0

    epoch_utc = float(npz["epoch_utc"])
    t = np.array([s.t_utc for s in fused]) - epoch_utc
    valid = np.array([is_valid(s) for s in fused])
    p = np.array([s.pos_enu for s in fused])
    v = np.array([s.vel_enu for s in fused])
    tp = np.column_stack([np.interp(t, npz["t"], npz["pos_enu"][:, i])
                          for i in range(3)])
    tv = np.column_stack([np.interp(t, npz["t"], npz["vel_enu"][:, i])
                          for i in range(3)])
    pos_rms = _rms((p - tp)[valid])
    vel_rms = _rms((v - tv)[valid])
    span = stats.t_last - stats.t_first
    continuity = stats.valid_time / span

    # ablation: no v_r updates — D3's architecture decision, measured
    from maiden.ingest import load
    samples = []
    for sp_ in sorted(Path(out_dir).glob("STATION_*.ch10")):
        samples.extend(load(sp_))
    azel_only = [s for s in samples if s.v_r is None]
    fused_nv, _ = fuse(azel_only, _stations)
    tn = np.array([s.t_utc for s in fused_nv]) - epoch_utc
    vn = np.array([s.vel_enu for s in fused_nv])
    valid_n = np.array([is_valid(s) for s in fused_nv])
    tvn = np.column_stack([np.interp(tn, npz["t"], npz["vel_enu"][:, i])
                           for i in range(3)])
    vel_rms_novr = _rms((vn - tvn)[valid_n])

    RESULTS13.mkdir(parents=True, exist_ok=True)
    with open(RESULTS13 / "headline.md", "w") as f:
        f.write(
            "# maiden25 headline run (SIM REHEARSAL)\n\n"
            "Twin seed 303, `--imperfect`, three stations, .ch10 round "
            "trip through ingest. VT-10/11/12 bind only in the field "
            "(lesson 99); these are necessary-not-sufficient numbers.\n\n"
            "| metric | value | threshold (D2, sim rehearsal) |\n"
            "|---|---|---|\n"
            f"| position RMS (valid epochs) | {pos_rms:.3f} m "
            f"| <= {POS_RMS_MAX} m (SYS-002) |\n"
            f"| velocity RMS (valid epochs) | {vel_rms:.3f} m/s "
            f"| <= {VEL_RMS_MAX} m/s (SYS-003) |\n"
            f"| continuity | {continuity:.4f} "
            f"| >= {CONTINUITY_MIN} (SYS-004) |\n"
            f"| gate rate | {100 * stats.gate_rate:.3f}% | < 1% |\n"
            f"| updates / gated | {stats.n_updates} / {stats.n_gated} | |\n"
            f"| coast time | {stats.coast_time:.2f} s | |\n\n"
            f"v_r ablation: velocity RMS {vel_rms_novr:.3f} m/s without "
            f"radials vs {vel_rms:.3f} m/s with — the delta is D3's "
            "three-radar architecture decision, measured. (Layout note: "
            "the twin's collinear A-B-C leaves one velocity component to "
            "the cameras; see test_fuse_vr.py.)\n")

    fig, ax = plt.subplots(figsize=(10, 4))
    err = np.linalg.norm(p - tp, axis=1)
    ax.plot(t, err, "b-", lw=0.7)
    ax.plot(t[~valid], err[~valid], "r.", ms=3, label="invalid epochs")
    ax.axhline(1.0, color="k", ls="--", lw=0.8, label="SYS-002 (sim)")
    ax.set_xlabel("t (s)")
    ax.set_ylabel("|pos error| (m)")
    ax.set_title(f"headline: pos RMS {pos_rms:.3f} m, vel RMS "
                 f"{vel_rms:.3f} m/s, continuity {continuity:.4f}")
    ax.legend()
    fig.savefig(RESULTS13 / "headline_error.png", dpi=110)
    plt.close(fig)

    assert pos_rms <= POS_RMS_MAX, f"pos RMS {pos_rms:.3f} m"
    assert vel_rms <= VEL_RMS_MAX, f"vel RMS {vel_rms:.3f} m/s"
    assert continuity >= CONTINUITY_MIN, f"continuity {continuity:.4f}"
    assert stats.gate_rate < 0.01, f"gate rate {stats.gate_rate:.4f}"
    assert vel_rms < vel_rms_novr, "v_r updates must help velocity"


def test_gating_protects_track(clean_ab):
    """30-sigma az outliers injected: gate rejects, RMS unchanged."""
    truth, poses, samples = clean_ab
    stations = {"A": poses["A"], "B": poses["B"]}
    fused_clean, stats_clean = fuse(samples, stations)

    poisoned = list(samples)
    sig_deg = np.degrees(0.5e-3)
    n_out = 0
    for i, s in enumerate(poisoned):
        if s.az_deg is not None and i % 197 == 0:
            poisoned[i] = StateSample(t_utc=s.t_utc, source=s.source,
                                      az_deg=s.az_deg + 30 * sig_deg,
                                      el_deg=s.el_deg, conf=s.conf)
            n_out += 1
    fused_p, stats_p = fuse(poisoned, stations)
    assert stats_p.n_gated >= 0.8 * n_out, (
        f"gated {stats_p.n_gated} of {n_out} injected outliers")

    def rms_of(fused):
        t = np.array([s.t_utc for s in fused])
        p = np.array([s.pos_enu for s in fused])
        return _rms(p - _truth_at(truth, t)[0])

    r_clean, r_p = rms_of(fused_clean), rms_of(fused_p)
    assert abs(r_p - r_clean) < 0.15, (r_clean, r_p)
    assert stats_clean.gate_rate < 0.01


def test_baseline_scaling_law(clean_ab):
    """maiden23 Explore: measured RMS vs baseline against R^2 sigma/B."""
    truth = sportsman(seed=202)
    rms_by_b = {}
    for b in (25.0, 75.0, 150.0):
        pa = Pose((0.0, 0.0, 0.0), 12.4)
        pb = Pose((b * np.cos(np.radians(12.4)),
                   -b * np.sin(np.radians(12.4)), 0.0), 8.0)
        poses = {"A": pa, "B": pb}
        streams = {n: observe(truth, poses[n],
                              rng=np.random.default_rng(700 + ord(n)),
                              dropout_p=0.0, outage=None)
                   for n in ("A", "B")}
        samples = _streams_to_samples(streams)
        fused = fuse_azel_only(samples, poses)
        t = np.array([s.t_utc for s in fused])
        p = np.array([s.pos_enu for s in fused])
        rms_by_b[b] = _rms(p - _truth_at(truth, t)[0])

    fig, ax = plt.subplots(figsize=(6, 4))
    bs = np.array(sorted(rms_by_b))
    meas = np.array([rms_by_b[b] for b in bs])
    pred = 150.0**2 * 0.5e-3 / bs
    ax.loglog(bs, meas, "o-", label="measured pos RMS")
    ax.loglog(bs, pred, "k--", label=r"D3: $R^2\sigma_\theta/B$ (range term)")
    ax.set_xlabel("baseline B (m)")
    ax.set_ylabel("RMS (m)")
    ax.legend()
    RESULTS12.mkdir(parents=True, exist_ok=True)
    fig.savefig(RESULTS12 / "baseline_scaling.png", dpi=110)
    plt.close(fig)

    # D3 promises ~3x degradation from 75 -> 25 m; the EKF smooths some
    # of it away, so accept >= 1.8x and monotone ordering.
    assert rms_by_b[25.0] > 1.8 * rms_by_b[75.0], rms_by_b
    assert rms_by_b[75.0] >= rms_by_b[150.0] * 0.8, rms_by_b


def test_azel_wrap_crossing_behind_station():
    """maiden23 break-it drill, automated. The subtlety the first version
    of this test taught: with per-frame updates and an accurate velocity,
    the PREDICTION crosses +-180 in the same frame as the measurement, so
    no 2-pi innovation appears — the wrap bug bites when the estimate
    lags across the seam (sparse updates, coast, or velocity error). So
    the drill uses a coasting filter: one update on the -170 deg side,
    the next on the +170 deg side."""
    pose = Pose((0.0, 0.0, 0.0), 0.0)
    p_before = np.array([-14.0, -80.0, 40.0])   # az ~ -170 deg
    p_after = np.array([+14.0, -80.0, 40.0])    # az ~ +170 deg

    def run(wrapped: bool):
        ekf = Ekf(EkfConfig(sigma_a=2.0))
        ekf.x = np.concatenate([p_before, np.zeros(3)])   # v unknown
        ekf.p = np.diag([1.0] * 3 + [100.0] * 3)
        ekf.t = 0.0
        for t, p_true in ((1.0, p_before), (2.0, p_after)):
            ekf.predict(t)
            zr = h_azel(p_true, pose)
            y = zr - h_azel(ekf.x[:3], pose)
            if wrapped:
                y[0] = (y[0] + np.pi) % (2 * np.pi) - np.pi
            from maiden.fuse import jac_azel
            h = jac_azel(ekf.x[:3], pose)
            r = np.eye(2) * (0.5e-3) ** 2
            ekf._apply(y, h, r)
        return np.linalg.norm(ekf.x[:3] - p_after)

    # coasting across the seam: prediction still on the -170 side when the
    # +170 measurement arrives -> ~340 deg innovation unless wrapped
    assert run(wrapped=True) < 30.0
    assert run(wrapped=False) > 3.0 * run(wrapped=True)
