/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.5. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module pm_adc
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire [7:0] half_period
    , input wire [2:0] aux_sel
    , input wire  miso

      // Outputs
    , output wire [51:0] adc
    );
  reg [112:0] c$ds_app_arg = {2'd0,   8'd4,   5'd24,   24'b000000000000000000000000,
 24'b000000000000000000000000,   2'd0,   {12'd0,   12'd0,   12'd0},   12'd0};
  reg  c$app_arg;
  reg  c$app_arg_0;
  reg  c$app_arg_1;
  wire signed [63:0] c$case_scrut;
  wire [112:0] c$app_arg_2;
  reg [112:0] c$case_alt;
  wire [112:0] c$case_alt_0;
  wire  c$case_scrut_0;
  wire [11:0] c$app_arg_3;
  wire [35:0] c$app_arg_4;
  wire [35:0] c$case_alt_1;
  wire [11:0] v;
  wire [2:0] z;
  wire [1:0] result;
  wire [2:0] c$app_arg_5;
  wire [2:0] c$app_arg_6;
  wire [2:0] c$case_alt_2;
  wire  c$case_scrut_1;
  wire [7:0] c$app_arg_7;
  wire [23:0] c$bv;
  wire [1:0] c$dtt_rhs_1;
  wire [1:0] c$case_alt_selection_1;
  wire [1:0] c$bv_0;
  wire [1:0] c$i_40;
  wire [35:0] c$vec;
  wire [23:0] c$bv_1;
  wire [2:0] c$bv_2;
  wire [1:0] c$bv_3;

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds_app_arg_register
    if ( rst) begin
      c$ds_app_arg <= {2'd0,   8'd4,   5'd24,   24'b000000000000000000000000,
   24'b000000000000000000000000,   2'd0,   {12'd0,   12'd0,   12'd0},   12'd0};
    end else if (en) begin
      c$ds_app_arg <= c$app_arg_2;
    end
  end
  // register end

  assign c$bv = (c$ds_app_arg[97:74]);

  assign adc = {c$app_arg_1,   c$app_arg_0,
                 c$bv[24-1] ,   c$ds_app_arg[47:12],
                c$ds_app_arg[11:0],
                (c$ds_app_arg[110:103] == 8'd0) & (c$app_arg & (c$case_scrut_0 & c$case_scrut_1))};

  always @(*) begin
    case(c$case_scrut)
      64'sd2 : c$app_arg = 1'b1;
      default : c$app_arg = 1'b0;
    endcase
  end

  always @(*) begin
    case(c$case_scrut)
      64'sd2 : c$app_arg_0 = 1'b1;
      default : c$app_arg_0 = 1'b0;
    endcase
  end

  always @(*) begin
    case(c$case_scrut)
      64'sd0 : c$app_arg_1 = 1'b1;
      default : c$app_arg_1 = 1'b0;
    endcase
  end

  assign c$dtt_rhs_1 = c$ds_app_arg[112:111];

  assign c$case_scrut = $unsigned(c$dtt_rhs_1);

  assign c$app_arg_2 = (c$ds_app_arg[110:103] != 8'd0) ? {c$ds_app_arg[112:111],
                                                          c$ds_app_arg[110:103] - 8'd1,
                                                          c$ds_app_arg[102:98],   c$ds_app_arg[97:74],
                                                          c$ds_app_arg[73:50],   c$ds_app_arg[49:48],
                                                          c$ds_app_arg[47:12],
                                                          c$ds_app_arg[11:0]} : c$case_alt;

  assign c$case_alt_selection_1 = c$ds_app_arg[112:111];

  always @(*) begin
    case(c$case_alt_selection_1)
      2'b00 : c$case_alt = {2'd1,   c$app_arg_7,
                            5'd24,
                            {({(8'b00000110 | ({7'b0000000,(c$app_arg_5[2 : 2])})),({(c$app_arg_5[1 : 0]),6'b000000})}),8'b00000000},
                            24'b000000000000000000000000,
                            c$ds_app_arg[49:48],   c$ds_app_arg[47:12],
                            c$ds_app_arg[11:0]};
      2'b01 : c$case_alt = {2'd2,   c$app_arg_7,
                            c$ds_app_arg[102:98],   c$ds_app_arg[97:74],
                            (c$ds_app_arg[73:50] << (64'sd1)) | ({23'b00000000000000000000000,((miso))}),
                            c$ds_app_arg[49:48],   c$ds_app_arg[47:12],
                            c$ds_app_arg[11:0]};
      default : c$case_alt = c$case_alt_0;
    endcase
  end

  assign c$case_alt_0 = c$case_scrut_0 ? {2'd0,
                                          (8'd2 * half_period) - 8'd1,
                                          c$ds_app_arg[102:98],   c$ds_app_arg[97:74],
                                          c$ds_app_arg[73:50],   result,   c$app_arg_4,
                                          c$app_arg_3} : {2'd1,   c$app_arg_7,
                                                          c$ds_app_arg[102:98] - 5'd1,
                                                          c$ds_app_arg[97:74] << (64'sd1),
                                                          c$ds_app_arg[73:50],   c$ds_app_arg[49:48],
                                                          c$ds_app_arg[47:12],   c$ds_app_arg[11:0]};

  assign c$case_scrut_0 = c$ds_app_arg[102:98] == 5'd1;

  assign c$app_arg_3 = c$case_scrut_1 ? v : c$ds_app_arg[11:0];

  assign c$app_arg_4 = (c$ds_app_arg[49:48] <= 2'd2) ? c$case_alt_1 : c$ds_app_arg[47:12];

  assign c$bv_0 = c$ds_app_arg[49:48];

  assign c$i_40 = (c$bv_0[0+:2]);

  assign c$vec = c$ds_app_arg[47:12];

  // vector replace begin
  genvar i;
  generate
  for (i=0;i<3;i=i+1) begin : vector_replace
    assign c$case_alt_1[(2-i)*12+:12] = ($unsigned({{(64-2) {1'b0}},c$i_40})) == i ? v : c$vec[(2-i)*12+:12];
  end
  endgenerate
  // vector replace end

  assign c$bv_1 = (c$ds_app_arg[73:50]);

  assign v = (c$bv_1[11 : 0]);

  assign z = c$ds_app_arg[49:48] + 2'd1;

  assign c$bv_2 = (z - 3'd4);

  assign result = (z >= 3'd4) ? (c$bv_2[0+:2]) : (z[0+:2]);

  assign c$app_arg_5 = c$app_arg_6;

  assign c$bv_3 = c$ds_app_arg[49:48];

  assign c$app_arg_6 = c$case_scrut_1 ? c$case_alt_2 : ((({{(3-2) {1'b0}},c$ds_app_arg[49:48]})));

  assign c$case_alt_2 = (aux_sel <= 3'b010) ? 3'b011 : aux_sel;

  assign c$case_scrut_1 = c$ds_app_arg[49:48] == 2'd3;

  assign c$app_arg_7 = half_period - 8'd1;


endmodule

