/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.10.0. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module pm_net_beacon
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire  go
    , input wire [7:0] mode

      // Outputs
    , output wire [1:0] txd
    , output wire  tx_en
    , output wire  ready
    );
  reg [112:0] c$ds_app_arg = {2'd0,   7'd0,   2'd0,   8'b00000000,   32'b11111111111111111111111111111111,
 32'b00000000000000000000000000000000,   8'b00000000,   16'd0,   6'd0};
  reg [116:0] c$case_alt;
  wire [116:0] c$case_alt_0;
  wire [116:0] c$case_alt_1;
  wire [112:0] result_0;
  wire [112:0] c$case_alt_2;
  wire [112:0] c$case_alt_3;
  wire [31:0] \crc' ;
  wire [7:0] c$app_arg;
  wire [31:0] c$app_arg_0;
  wire [7:0] c$app_arg_1;
  wire [7:0] result_1;
  wire [7:0] c$case_alt_4;
  wire [7:0] c$case_alt_5;
  wire [7:0] c$case_alt_6;
  wire [15:0] c$app_arg_2;
  wire [159:0] c$app_arg_3;
  wire [31:0] result_2;
  wire [31:0] result_3;
  wire [351:0] ws;
  wire [319:0] ws1;
  wire [6:0] c$app_arg_4;
  wire  b;
  wire [31:0] result_4;
  wire [31:0] c$app_arg_5;
  wire  b_0;
  wire [31:0] result_5;
  wire [31:0] c$app_arg_6;
  wire [1:0] c$app_arg_7;
  wire [1:0] txd_1;
  wire  inData;
  wire [7:0] c$app_arg_8;
  wire [159:0] c$app_arg_9;
  wire [31:0] result_6;
  wire [31:0] result_7;
  wire [351:0] ws_0;
  wire [319:0] ws1_0;
  wire [1:0] c$case_alt_selection_1;
  wire [71:0] c$case_alt_res;
  wire [188:0] c$vec;
  wire [6:0] c$i_59;
  wire [543:0] c$vecFlat;
  wire [31:0] c$bv;
  wire [159:0] c$vec_0;
  wire [159:0] c$vec1;
  wire [319:0] c$vec2;
  wire [31:0] c$bv_0;
  wire [31:0] c$bv_1;
  wire [7:0] c$bv_2;
  wire [31:0] c$bv_3;
  wire [71:0] c$app_arg_res;
  wire [188:0] c$vec_1;
  wire [543:0] c$vec_2;
  wire [31:0] c$bv_4;
  wire [159:0] c$vec_3;
  wire [159:0] c$vec1_0;
  wire [319:0] c$vec2_0;
  wire [3:0] result;

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$ds_app_arg_register
    if ( rst) begin
      c$ds_app_arg <= {2'd0,   7'd0,   2'd0,   8'b00000000,   32'b11111111111111111111111111111111,
   32'b00000000000000000000000000000000,   8'b00000000,   16'd0,   6'd0};
    end else if (en) begin
      c$ds_app_arg <= c$case_alt[116:4];
    end
  end
  // register end

  assign result = c$case_alt[3:0];

  assign c$case_alt_selection_1 = c$ds_app_arg[112:111];

  always @(*) begin
    case(c$case_alt_selection_1)
      2'b00 : c$case_alt = c$case_alt_1;
      2'b01 : c$case_alt = {result_0,   {txd_1,
                                         1'b1,   1'b0}};
      default : c$case_alt = c$case_alt_0;
    endcase
  end

  assign c$case_alt_0 = (c$ds_app_arg[5:0] == 6'd47) ? {{2'd0,
                                                         c$ds_app_arg[110:104],
                                                         c$ds_app_arg[103:102],   c$ds_app_arg[101:94],
                                                         c$ds_app_arg[93:62],   c$ds_app_arg[61:30],
                                                         c$ds_app_arg[29:22],
                                                         c$ds_app_arg[21:6] + 16'd1,
                                                         c$ds_app_arg[5:0]},   {2'b00,   1'b0,
                                                                                1'b0}} : {{2'd2,
                                                                                           c$ds_app_arg[110:104],
                                                                                           c$ds_app_arg[103:102],
                                                                                           c$ds_app_arg[101:94],
                                                                                           c$ds_app_arg[93:62],
                                                                                           c$ds_app_arg[61:30],
                                                                                           c$ds_app_arg[29:22],
                                                                                           c$ds_app_arg[21:6],
                                                                                           c$ds_app_arg[5:0] + 6'd1},
                                                                                          {2'b00,   1'b0,   1'b0}};

  assign c$case_alt_1 = go ? {{2'd1,   7'd0,
                               2'd0,   c$app_arg_8,
                               32'b11111111111111111111111111111111,
                               c$ds_app_arg[61:30],   mode,
                               c$ds_app_arg[21:6],   c$ds_app_arg[5:0]},
                              {2'b00,   1'b0,   1'b1}} : {c$ds_app_arg,
                                                          {2'b00,   1'b0,   1'b1}};

  assign result_0 = (c$ds_app_arg[103:102] != 2'd3) ? {2'd1,
                                                       c$ds_app_arg[110:104],
                                                       c$ds_app_arg[103:102] + 2'd1,   c$app_arg,
                                                       \crc' ,   c$app_arg_0,   c$ds_app_arg[29:22],
                                                       c$ds_app_arg[21:6],
                                                       c$ds_app_arg[5:0]} : c$case_alt_2;

  assign c$case_alt_2 = (c$ds_app_arg[110:104] == 7'd71) ? {2'd2,
                                                            c$ds_app_arg[110:104],
                                                            c$ds_app_arg[103:102],   c$ds_app_arg[101:94],
                                                            c$ds_app_arg[93:62],   c$ds_app_arg[61:30],
                                                            c$ds_app_arg[29:22],   c$ds_app_arg[21:6],
                                                            6'd0} : c$case_alt_3;

  assign c$case_alt_3 = (c$ds_app_arg[110:104] == 7'd67) ? {2'd1,
                                                            7'd68,   2'd0,   c$app_arg,   \crc' ,
                                                            ~ \crc' ,   c$ds_app_arg[29:22],
                                                            c$ds_app_arg[21:6],
                                                            c$ds_app_arg[5:0]} : {2'd1,   c$app_arg_4,
                                                                                  2'd0,   c$app_arg_1,   \crc' ,
                                                                                  c$app_arg_0,   c$ds_app_arg[29:22],
                                                                                  c$ds_app_arg[21:6],
                                                                                  c$ds_app_arg[5:0]};

  assign \crc'  = (inData & (c$ds_app_arg[110:104] >= 7'd8)) ? result_4 : c$ds_app_arg[93:62];

  assign c$app_arg = c$ds_app_arg[101:94] >> (64'sd2);

  assign c$app_arg_0 = inData ? c$ds_app_arg[61:30] : (c$ds_app_arg[61:30] >> (64'sd2));

  assign c$app_arg_1 = (c$ds_app_arg[110:104] < 7'd67) ? result_1 : c$ds_app_arg[101:94];

  assign result_1 = ((c$app_arg_4[0+:7]) == 7'd59) ? c$ds_app_arg[29:22] : c$case_alt_4;

  assign c$case_alt_4 = ((c$app_arg_4[0+:7]) == 7'd60) ? (c$app_arg_2[15 : 8]) : c$case_alt_5;

  assign c$case_alt_5 = ((c$app_arg_4[0+:7]) == 7'd61) ? (c$app_arg_2[7 : 0]) : c$case_alt_6;

  assign c$vec = {21'd80,   21'd77,   21'd45,
                  21'd79,   21'd78,   21'd69,   21'd66,
                  21'd79,   21'd88};

  // map begin
  genvar i;
  generate
  for (i=0; i < 9; i = i + 1) begin : map
    localparam vec_index = 8 - i;
    wire [20:0] map_in;
    assign map_in = c$vec[vec_index*21+:21];
    wire [7:0] map_out;
    wire [20:0] \c# ;
    wire [7:0] c$case_alt_11;
    wire signed [63:0] c$app_arg_12;
    assign map_out = c$case_alt_11;

    assign \c#  = map_in;

    assign c$case_alt_11 = $unsigned(c$app_arg_12[0+:8]);

    assign c$app_arg_12 = $signed({{(64-21) {1'b0}},\c# });


    assign c$case_alt_res[vec_index*8+:8] = map_out;
  end
  endgenerate
  // map end

  assign c$i_59 = (c$app_arg_4[0+:7]);

  assign c$vecFlat = ({({7 {8'b01010101}}),({8'b11010101,({({6 {8'b11111111}}),({{8'b00000010,   8'b01010000,   8'b01001101,   8'b00000000,   8'b00000000,
 8'b00000001},({{8'b00001000,   8'b00000000},({(c$app_arg_3),({{8'b01010000,   8'b01001101,   8'b01010000,   8'b01001101,   8'b00000000,
 8'b00011000,   8'b00000000,   8'b00000000},({c$case_alt_res,({({7 {8'b00000000}}),({2 {8'b00000000}})})})})})})})})})});

  // index begin
  wire [7:0] vecArray [0:68-1];
  genvar i_0;
  generate
  for (i_0=0; i_0 < 68; i_0=i_0+1) begin : mk_array
    assign vecArray[(68-1)-i_0] = c$vecFlat[i_0*8+:8];
  end
  endgenerate
  assign c$case_alt_6 = vecArray[($unsigned({{(64-7) {1'b0}},c$i_59}))];
  // index end

  assign c$app_arg_2 = ((c$ds_app_arg[21:6]));

  assign c$bv = ((result_2 & 32'b00000000000000001111111111111111) + (result_2 >> (64'sd16)));

  assign c$vec_0 = {16'b0100010100000000,
                    16'b0000000000101100,   16'b0000000000000000,
                    16'b0000000000000000,   16'b0100000000010001,
                    ~ (c$bv[0+:16]),   16'b0000101000000000,
                    16'b0000000001001101,   16'b1111111111111111,
                    16'b1111111111111111};

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 10; i_1 = i_1 + 1) begin : map_0
    localparam vec_index_0 = 9 - i_1;
    wire [15:0] map_in_0;
    assign map_in_0 = c$vec_0[vec_index_0*16+:16];
    wire [15:0] map_out_0;
    wire [15:0] result_9;
    wire [15:0] c$app_arg_13;
    assign map_out_0 = result_9;

    assign result_9 = {c$app_arg_13[15 : 8],
                       c$app_arg_13[7 : 0]};

    assign c$app_arg_13 = map_in_0;


    assign c$app_arg_3[vec_index_0*16+:16] = map_out_0;
  end
  endgenerate
  // map end

  assign result_2 = (result_3 & 32'b00000000000000001111111111111111) + (result_3 >> (64'sd16));

  assign result_3 = ws[32-1:0];

  assign ws = {32'b00000000000000000000000000000000,
               ws1};

  assign c$vec1 = {16'b0100010100000000,
                   16'b0000000000101100,   16'b0000000000000000,
                   16'b0000000000000000,   16'b0100000000010001,
                   16'b0000000000000000,   16'b0000101000000000,
                   16'b0000000001001101,   16'b1111111111111111,
                   16'b1111111111111111};

  assign c$vec2 = (ws[352-1 : 32]);

  // zipWith start
  genvar i_2;
  generate
  for (i_2 = 0; i_2 < 10; i_2 = i_2 + 1) begin : zipWith
    localparam vec_index_1 = 9 - i_2;
    wire [15:0] zipWith_in1;
    assign zipWith_in1 = c$vec1[vec_index_1*16+:16];
    wire [31:0] zipWith_in2;
    assign zipWith_in2 = c$vec2[vec_index_1*32+:32];
    wire [31:0] zip_out;
    assign zip_out = zipWith_in2 + ({16'b0000000000000000,zipWith_in1});


    assign ws1[vec_index_1*32+:32] = zip_out;
  end
  endgenerate
  // zipWith end

  assign c$app_arg_4 = c$ds_app_arg[110:104] + 7'd1;

  assign b = c$app_arg_7[(64'sd1)];

  assign c$bv_0 = (result_5);

  assign result_4 = ((b ^ ( c$bv_0[0] )) == 1'b1) ? (c$app_arg_5 ^ 32'b11101101101110001000001100100000) : c$app_arg_5;

  assign c$app_arg_5 = result_5 >> (64'sd1);

  assign b_0 = c$app_arg_7[(64'sd0)];

  assign c$bv_1 = (c$ds_app_arg[93:62]);

  assign result_5 = ((b_0 ^ ( c$bv_1[0] )) == 1'b1) ? (c$app_arg_6 ^ 32'b11101101101110001000001100100000) : c$app_arg_6;

  assign c$app_arg_6 = c$ds_app_arg[93:62] >> (64'sd1);

  assign c$app_arg_7 = txd_1;

  assign c$bv_2 = c$ds_app_arg[101:94];

  assign c$bv_3 = c$ds_app_arg[61:30];

  assign txd_1 = inData ? (c$bv_2[0+:2]) : (c$bv_3[0+:2]);

  assign inData = c$ds_app_arg[110:104] <= 7'd67;

  assign c$vec_1 = {21'd80,   21'd77,   21'd45,
                    21'd79,   21'd78,   21'd69,   21'd66,
                    21'd79,   21'd88};

  // map begin
  genvar i_3;
  generate
  for (i_3=0; i_3 < 9; i_3 = i_3 + 1) begin : map_1
    localparam vec_index_2 = 8 - i_3;
    wire [20:0] map_in_1;
    assign map_in_1 = c$vec_1[vec_index_2*21+:21];
    wire [7:0] map_out_1;
    wire [20:0] \c#_1 ;
    wire [7:0] c$case_alt_12;
    wire signed [63:0] c$app_arg_14;
    assign map_out_1 = c$case_alt_12;

    assign \c#_1  = map_in_1;

    assign c$case_alt_12 = $unsigned(c$app_arg_14[0+:8]);

    assign c$app_arg_14 = $signed({{(64-21) {1'b0}},\c#_1 });


    assign c$app_arg_res[vec_index_2*8+:8] = map_out_1;
  end
  endgenerate
  // map end

  assign c$vec_2 = ({({7 {8'b01010101}}),({8'b11010101,({({6 {8'b11111111}}),({{8'b00000010,   8'b01010000,   8'b01001101,   8'b00000000,   8'b00000000,
 8'b00000001},({{8'b00001000,   8'b00000000},({(c$app_arg_9),({{8'b01010000,   8'b01001101,   8'b01010000,   8'b01001101,   8'b00000000,
 8'b00011000,   8'b00000000,   8'b00000000},({c$app_arg_res,({({7 {8'b00000000}}),({2 {8'b00000000}})})})})})})})})})});

  // index lit begin
  assign c$app_arg_8 = c$vec_2[544-1-0*8 -: 8];
  // index lit end

  assign c$bv_4 = ((result_6 & 32'b00000000000000001111111111111111) + (result_6 >> (64'sd16)));

  assign c$vec_3 = {16'b0100010100000000,
                    16'b0000000000101100,   16'b0000000000000000,
                    16'b0000000000000000,   16'b0100000000010001,
                    ~ (c$bv_4[0+:16]),   16'b0000101000000000,
                    16'b0000000001001101,   16'b1111111111111111,
                    16'b1111111111111111};

  // map begin
  genvar i_4;
  generate
  for (i_4=0; i_4 < 10; i_4 = i_4 + 1) begin : map_2
    localparam vec_index_3 = 9 - i_4;
    wire [15:0] map_in_2;
    assign map_in_2 = c$vec_3[vec_index_3*16+:16];
    wire [15:0] map_out_2;
    wire [15:0] result_10;
    wire [15:0] c$app_arg_15;
    assign map_out_2 = result_10;

    assign result_10 = {c$app_arg_15[15 : 8],
                        c$app_arg_15[7 : 0]};

    assign c$app_arg_15 = map_in_2;


    assign c$app_arg_9[vec_index_3*16+:16] = map_out_2;
  end
  endgenerate
  // map end

  assign result_6 = (result_7 & 32'b00000000000000001111111111111111) + (result_7 >> (64'sd16));

  assign result_7 = ws_0[32-1:0];

  assign ws_0 = {32'b00000000000000000000000000000000,
                 ws1_0};

  assign c$vec1_0 = {16'b0100010100000000,
                     16'b0000000000101100,   16'b0000000000000000,
                     16'b0000000000000000,   16'b0100000000010001,
                     16'b0000000000000000,   16'b0000101000000000,
                     16'b0000000001001101,   16'b1111111111111111,
                     16'b1111111111111111};

  assign c$vec2_0 = (ws_0[352-1 : 32]);

  // zipWith start
  genvar i_5;
  generate
  for (i_5 = 0; i_5 < 10; i_5 = i_5 + 1) begin : zipWith_0
    localparam vec_index_4 = 9 - i_5;
    wire [15:0] zipWith_in1_0;
    assign zipWith_in1_0 = c$vec1_0[vec_index_4*16+:16];
    wire [31:0] zipWith_in2_0;
    assign zipWith_in2_0 = c$vec2_0[vec_index_4*32+:32];
    wire [31:0] zip_out_0;
    assign zip_out_0 = zipWith_in2_0 + ({16'b0000000000000000,zipWith_in1_0});


    assign ws1_0[vec_index_4*32+:32] = zip_out_0;
  end
  endgenerate
  // zipWith end

  assign txd = result[3:2];

  assign tx_en = result[1:1];

  assign ready = result[0:0];


endmodule
`default_nettype wire

