apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - networkpolicy.yaml
  - pdb.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: poetic-musings
    includeSelectors: true
