apiVersion: v1
kind: Service
metadata:
  name: status-service
  labels:
    app.kubernetes.io/name: status-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: status-service
  ports:
    - name: http
      port: 80
      targetPort: http
