/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.5. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module pm_matrix
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire [15:0] matrix_ctrl
    , input wire  ikeys_re
    , input wire [7:0] col_n

      // Outputs
    , output wire [7:0] row_n
    , output wire [15:0] ikeys
    );
  wire [7:0] c$ds_app_arg;
  wire  v;
  reg [619:0] s1 = {1'b0,   3'd0,   12'd0,   {1'b0,   1'b0,   1'b0,   1'b0,   1'b0,   1'b0,
                           1'b0,   1'b0},   3'd0,   3'd0,   1'b0,   {1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0,
                                                                     1'b0},
 {6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
  6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
  6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
  6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
  6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
  6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
  6'd0,   6'd0,   6'd0,   6'd0},   {8'b00000000,   8'b00000000,   8'b00000000,
                                    8'b00000000,   8'b00000000,   8'b00000000,
                                    8'b00000000,   8'b00000000,   8'b00000000,
                                    8'b00000000,   8'b00000000,   8'b00000000,
                                    8'b00000000,   8'b00000000,   8'b00000000,
                                    8'b00000000},   4'd0,   4'd0,   5'd0};
  wire [7:0] c$app_arg;
  wire [0:0] c$app_arg_0;
  wire [7:0] c$app_arg_1;
  wire [383:0] c$app_arg_2;
  wire [383:0] c$case_alt;
  wire [383:0] c$case_alt_0;
  wire [383:0] c$case_alt_1;
  wire  result_0;
  wire [63:0] c$app_arg_3;
  wire [63:0] c$case_alt_2;
  wire [136:0] result_1;
  wire  flips;
  wire [4:0] z;
  wire [3:0] result_2;
  wire [127:0] c$ds10_case_alt;
  wire [0:0] c$ds10_app_arg;
  wire [3:0] wr0;
  wire [4:0] n1;
  wire  c$flips_app_arg;
  wire [6:0] r;
  wire [5:0] result_3;
  reg  result_4;
  wire signed [63:0] c$flips_case_scrut;
  wire signed [63:0] \b# ;
  wire signed [63:0] \a# ;
  wire [5:0] c$hits_case_alt;
  wire  c$curSt_case_alt;
  wire signed [63:0] c$curSt_app_arg;
  wire [5:0] kIx;
  wire  c$sampl_case_alt;
  wire [8:0] result_5;
  wire [3:0] c$ds9_app_arg;
  wire [4:0] z_0;
  wire [3:0] result_6;
  wire [3:0] c$ds9_app_arg_0;
  wire [4:0] n0;
  wire [29:0] result_7;
  wire [29:0] c$ds8_case_alt;
  wire  \procBusy' ;
  wire [7:0] c$ds8_app_arg;
  wire [3:0] z_1;
  wire [2:0] result_8;
  wire [2:0] \c$procIx'_case_alt ;
  wire [3:0] z_2;
  wire [2:0] result_9;
  wire [7:0] c$app_arg_4;
  wire [7:0] c$vec;
  wire [15:0] c$bv;
  wire [7:0] s1_1;
  wire [23:0] c$app_arg_res;
  wire [3:0] c$i_177;
  wire [127:0] c$vecFlat;
  wire [383:0] c$vec_0;
  wire [383:0] c$vec_1;
  wire [63:0] c$vec_2;
  wire [4:0] c$bv_0;
  wire [127:0] c$vec_3;
  wire [15:0] c$bv_1;
  wire [7:0] wr0_selection_0;
  wire [15:0] c$bv_2;
  wire [7:0] c$flips_app_arg_selection_1;
  wire [15:0] c$bv_3;
  wire [7:0] c$flips_app_arg_sel_alt_f_1;
  wire [6:0] c$bv_4;
  wire [383:0] c$vecFlat_0;
  wire [63:0] c$vecFlat_1;
  wire [2:0] c$i_194;
  wire [7:0] c$vecFlat_2;
  wire [15:0] c$bv_5;
  wire [7:0] c$ds9_app_arg_selection_0;
  wire [4:0] c$bv_6;
  wire [15:0] c$bv_7;
  wire [7:0] c$ds9_app_arg_selection_2;
  wire [15:0] c$bv_8;
  wire [7:0] n0_selection_0;
  wire [3:0] c$bv_9;
  wire [3:0] c$bv_10;
  wire [23:0] c$app_arg_4_14;
  wire [7:0] c$vec_4;
  wire [23:0] result_dc_arg_0;
  wire [23:0] result;

  assign c$vec = ((col_n));

  // reverse begin
  genvar i;
  generate
  for (i = 0; i < 8; i = i + 1) begin : reverse
    assign c$ds_app_arg[(8 - 1 - i)*1+:1] = c$vec[i*1+:1];
  end
  endgenerate
  // reverse end

  assign v = ((ikeys_re)) == 1'b1;

  assign c$bv = (matrix_ctrl);

  assign s1_1 = {(matrix_ctrl[(64'sd0)]) == (1'b1),
                 (matrix_ctrl[(64'sd1)]) == (1'b1),
                 (c$bv[9 : 4])};

  // register begin
  always @(posedge clk or  posedge  rst) begin : s1_register
    if ( rst) begin
      s1 <= {1'b0,   3'd0,   12'd0,   {1'b0,   1'b0,   1'b0,   1'b0,   1'b0,   1'b0,
                             1'b0,   1'b0},   3'd0,   3'd0,   1'b0,   {1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0,
                                                                       1'b0},
   {6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
    6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
    6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
    6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
    6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
    6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,   6'd0,
    6'd0,   6'd0,   6'd0,   6'd0},   {8'b00000000,   8'b00000000,   8'b00000000,
                                      8'b00000000,   8'b00000000,   8'b00000000,
                                      8'b00000000,   8'b00000000,   8'b00000000,
                                      8'b00000000,   8'b00000000,   8'b00000000,
                                      8'b00000000,   8'b00000000,   8'b00000000,
                                      8'b00000000},   4'd0,   4'd0,   5'd0};
    end else if (en) begin
      s1 <= {s1_1[7:7],   result_7[29:27],   result_7[26:15],   result_7[14:7],
   result_7[6:4],   result_7[3:1],   result_7[0:0],   c$app_arg_3,   c$app_arg_2,
   result_1[136:9],   result_5[8:5],   result_1[8:5],   result_1[4:0]};
    end
  end
  // register end

  // imap begin
  genvar i_0;
  generate
  for (i_0=0; i_0 < 8; i_0 = i_0 + 1) begin : imap
    wire [3-1:0] map_index;
    wire [2:0] map_out;

    assign map_index = 3'd7 - i_0[0+:3];
    assign map_out = map_index;


    assign c$app_arg_res[i_0*3+:3] = map_out;
  end
  endgenerate
  // imap end

  // map begin
  genvar i_1;
  generate
  for (i_1=0; i_1 < 8; i_1 = i_1 + 1) begin : map
    wire [2:0] map_in_0;
    assign map_in_0 = c$app_arg_res[i_1*3+:3];
    wire  map_out_0;
    wire  result_10;
    assign map_out_0 = result_10;

    assign result_10 = (s1[619:619] & (map_in_0 == s1[618:616])) ? (1'b0) : (1'b1);


    assign c$app_arg[i_1*1+:1] = map_out_0;
  end
  endgenerate
  // map end

  assign c$app_arg_0 = (s1[4:0] != 5'd0) ? 1'b1 : 1'b0;

  assign c$i_177 = s1[12:9];

  assign c$vecFlat = s1[140:13];

  // index begin
  wire [7:0] vecArray [0:16-1];
  genvar i_2;
  generate
  for (i_2=0; i_2 < 16; i_2=i_2+1) begin : mk_array
    assign vecArray[(16-1)-i_2] = c$vecFlat[i_2*8+:8];
  end
  endgenerate
  assign c$app_arg_1 = vecArray[($unsigned({{(64-4) {1'b0}},c$i_177}))];
  // index end

  assign c$app_arg_2 = (~ s1[589:589]) ? s1[524:141] : c$case_alt;

  assign c$case_alt = (result_0 | flips) ? c$case_alt_0 : c$case_alt_1;

  assign c$vec_0 = s1[524:141];

  // vector replace begin
  genvar i_3;
  generate
  for (i_3=0;i_3<64;i_3=i_3+1) begin : vector_replace
    assign c$case_alt_0[(63-i_3)*6+:6] = c$curSt_app_arg == i_3 ? 6'd0 : c$vec_0[(63-i_3)*6+:6];
  end
  endgenerate
  // vector replace end

  assign c$vec_1 = s1[524:141];

  // vector replace begin
  genvar i_4;
  generate
  for (i_4=0;i_4<64;i_4=i_4+1) begin : vector_replace_0
    assign c$case_alt_1[(63-i_4)*6+:6] = c$curSt_app_arg == i_4 ? result_3 : c$vec_1[(63-i_4)*6+:6];
  end
  endgenerate
  // vector replace end

  assign result_0 = c$flips_case_scrut[0];

  assign c$app_arg_3 = flips ? c$case_alt_2 : s1[588:525];

  assign c$vec_2 = s1[588:525];

  // vector replace begin
  genvar i_5;
  generate
  for (i_5=0;i_5<64;i_5=i_5+1) begin : vector_replace_1
    assign c$case_alt_2[(63-i_5)*1+:1] = c$curSt_app_arg == i_5 ? c$sampl_case_alt : c$vec_2[(63-i_5)*1+:1];
  end
  endgenerate
  // vector replace end

  assign result_1 = (flips & (n1 != 5'd16)) ? {c$ds10_case_alt,
                                               result_2,   n1 + 5'd1} : {s1[140:13],   wr0,
                                                                         n1};

  assign flips = s1[589:589] & (result_4 & c$flips_app_arg);

  assign z = wr0 + 4'd1;

  assign c$bv_0 = (z - 5'd16);

  assign result_2 = (z >= 5'd16) ? (c$bv_0[0+:4]) : (z[0+:4]);

  assign c$vec_3 = s1[140:13];

  // vector replace begin
  genvar i_6;
  generate
  for (i_6=0;i_6<16;i_6=i_6+1) begin : vector_replace_2
    assign c$ds10_case_alt[(15-i_6)*8+:8] = ($unsigned({{(64-4) {1'b0}},wr0})) == i_6 ? ({({(c$ds10_app_arg),1'b0}),(((((kIx)))))}) : c$vec_3[(15-i_6)*8+:8];
  end
  endgenerate
  // vector replace end

  assign c$ds10_app_arg = c$sampl_case_alt ? 1'b1 : 1'b0;

  assign c$bv_1 = (matrix_ctrl);

  assign wr0_selection_0 = {(matrix_ctrl[(64'sd0)]) == (1'b1),
                            (matrix_ctrl[(64'sd1)]) == (1'b1),
                            (c$bv_1[9 : 4])};

  assign wr0 = wr0_selection_0[6:6] ? 4'd0 : s1[8:5];

  assign n1 = result_5[4:0];

  assign c$bv_2 = (matrix_ctrl);

  assign c$flips_app_arg_selection_1 = {(matrix_ctrl[(64'sd0)]) == (1'b1),
                                        (matrix_ctrl[(64'sd1)]) == (1'b1),
                                        (c$bv_2[9 : 4])};

  assign c$bv_3 = (matrix_ctrl);

  assign c$flips_app_arg_sel_alt_f_1 = {(matrix_ctrl[(64'sd0)]) == (1'b1),
                                        (matrix_ctrl[(64'sd1)]) == (1'b1),
                                        (c$bv_3[9 : 4])};

  assign c$flips_app_arg = (c$flips_app_arg_selection_1[5:0] == 6'd0) ? (result_3 >= 6'd10) : (result_3 >= c$flips_app_arg_sel_alt_f_1[5:0]);

  assign r = c$hits_case_alt + 6'd1;

  assign c$bv_4 = ((r));

  assign result_3 = (( c$bv_4[7-1] ) == 1'b0) ? (r[0+:6]) : 6'd63;

  always @(*) begin
    case(c$flips_case_scrut)
      64'sd1 : result_4 = 1'b0;
      default : result_4 = 1'b1;
    endcase
  end

  assign c$flips_case_scrut = (\a#  == \b# ) ? 64'sd1 : 64'sd0;

  assign \b#  = $unsigned({{63 {1'b0}},
                           c$curSt_case_alt});

  assign \a#  = $unsigned({{63 {1'b0}},
                           c$sampl_case_alt});

  assign c$vecFlat_0 = s1[524:141];

  // index begin
  wire [5:0] vecArray_0 [0:64-1];
  genvar i_7;
  generate
  for (i_7=0; i_7 < 64; i_7=i_7+1) begin : mk_array_0
    assign vecArray_0[(64-1)-i_7] = c$vecFlat_0[i_7*6+:6];
  end
  endgenerate
  assign c$hits_case_alt = vecArray_0[c$curSt_app_arg];
  // index end

  assign c$vecFlat_1 = s1[588:525];

  // index begin
  wire  vecArray_1 [0:64-1];
  genvar i_8;
  generate
  for (i_8=0; i_8 < 64; i_8=i_8+1) begin : mk_array_1
    assign vecArray_1[(64-1)-i_8] = c$vecFlat_1[i_8*1+:1];
  end
  endgenerate
  assign c$curSt_case_alt = vecArray_1[c$curSt_app_arg];
  // index end

  assign c$curSt_app_arg = $unsigned({{(64-6) {1'b0}},kIx});

  assign kIx = ({((s1[595:593])),((s1[592:590]))});

  assign c$i_194 = s1[592:590];

  assign c$vecFlat_2 = s1[603:596];

  // index begin
  wire  vecArray_2 [0:8-1];
  genvar i_9;
  generate
  for (i_9=0; i_9 < 8; i_9=i_9+1) begin : mk_array_2
    assign vecArray_2[(8-1)-i_9] = c$vecFlat_2[i_9*1+:1];
  end
  endgenerate
  assign c$sampl_case_alt = vecArray_2[($unsigned({{(64-3) {1'b0}},c$i_194}))];
  // index end

  assign result_5 = (v & (n0 != 5'd0)) ? {c$ds9_app_arg,
                                          n0 - 5'd1} : {c$ds9_app_arg_0,   n0};

  assign c$bv_5 = (matrix_ctrl);

  assign c$ds9_app_arg_selection_0 = {(matrix_ctrl[(64'sd0)]) == (1'b1),
                                      (matrix_ctrl[(64'sd1)]) == (1'b1),
                                      (c$bv_5[9 : 4])};

  assign c$ds9_app_arg = c$ds9_app_arg_selection_0[6:6] ? 4'd1 : result_6;

  assign z_0 = s1[12:9] + 4'd1;

  assign c$bv_6 = (z_0 - 5'd16);

  assign result_6 = (z_0 >= 5'd16) ? (c$bv_6[0+:4]) : (z_0[0+:4]);

  assign c$bv_7 = (matrix_ctrl);

  assign c$ds9_app_arg_selection_2 = {(matrix_ctrl[(64'sd0)]) == (1'b1),
                                      (matrix_ctrl[(64'sd1)]) == (1'b1),
                                      (c$bv_7[9 : 4])};

  assign c$ds9_app_arg_0 = c$ds9_app_arg_selection_2[6:6] ? 4'd0 : s1[12:9];

  assign c$bv_8 = (matrix_ctrl);

  assign n0_selection_0 = {(matrix_ctrl[(64'sd0)]) == (1'b1),
                           (matrix_ctrl[(64'sd1)]) == (1'b1),
                           (c$bv_8[9 : 4])};

  assign n0 = n0_selection_0[6:6] ? 5'd0 : s1[4:0];

  assign result_7 = (~ s1[619:619]) ? {s1[618:616],
                                       12'd0,   s1[603:596],   s1[595:593],
                                       \c$procIx'_case_alt ,
                                       \procBusy' } : c$ds8_case_alt;

  assign c$ds8_case_alt = (s1[619:619] & (s1[615:604] == 12'd3124)) ? {result_8,
                                                                       12'd0,   c$ds8_app_arg,   s1[618:616],   3'd0,
                                                                       1'b1} : {s1[618:616],   s1[615:604] + 12'd1,
                                                                                s1[603:596],   s1[595:593],
                                                                                \c$procIx'_case_alt ,   \procBusy' };

  assign \procBusy'  = s1[589:589] & (s1[592:590] != 3'd7);

  // map begin
  genvar i_10;
  generate
  for (i_10=0; i_10 < 8; i_10 = i_10 + 1) begin : map_0
    wire  map_in_1;
    assign map_in_1 = c$ds_app_arg[i_10*1+:1];
    wire  map_out_1;
    assign map_out_1 = map_in_1 == (1'b0);


    assign c$ds8_app_arg[i_10*1+:1] = map_out_1;
  end
  endgenerate
  // map end

  assign z_1 = s1[618:616] + 3'd1;

  assign c$bv_9 = (z_1 - 4'd8);

  assign result_8 = (z_1 >= 4'd8) ? (c$bv_9[0+:3]) : (z_1[0+:3]);

  assign \c$procIx'_case_alt  = s1[589:589] ? result_9 : s1[592:590];

  assign z_2 = s1[592:590] + 3'd1;

  assign c$bv_10 = (z_2 - 4'd8);

  assign result_9 = (z_2 >= 4'd8) ? (c$bv_10[0+:3]) : (z_2[0+:3]);

  assign c$app_arg_4_14 = {c$app_arg,
                           {({(c$app_arg_0),7'b0000000}),c$app_arg_1}};

  assign c$vec_4 = c$app_arg_4_14[23:16];

  // reverse begin
  genvar i_11;
  generate
  for (i_11 = 0; i_11 < 8; i_11 = i_11 + 1) begin : reverse_0
    assign c$app_arg_4[(8 - 1 - i_11)*1+:1] = c$vec_4[i_11*1+:1];
  end
  endgenerate
  // reverse end

  assign result_dc_arg_0 = {c$app_arg,
                            {({(c$app_arg_0),7'b0000000}),c$app_arg_1}};

  assign result = {((c$app_arg_4)),
                   result_dc_arg_0[15:0]};

  assign row_n = result[23:16];

  assign ikeys = result[15:0];


endmodule

